# If none are explicitly active when the application context starts, the default profiles are activated.
# So, in the following YAML, we set a value for spring.security.user.password that is available only in the "default" profile
# https://www.mkyong.com/spring/spring-propertysources-example/
# parkjs:
# # 반드시 클론(:)뒤에 스페이스바를 넣어줘야함.(어짜피 내부적으로 .yml -> .properties 형식으로 변환한다.)
#     name: park_yml_profile_none
# ---

# Relaxed binding 
spring:
    profiles: default
testproperties:
    time1: 1000
    time2: PT10H
    time3: 10s
    number1: 10
    number2: ${testproperties.time1}
    work-for: home_default
    whereToGo: where_to_go_default
    foo_bar: foobar_default
    name: park_yml_profile_default
    pojoList:
        - name: pojo1_name_default
          desc: pojo1_desc_default
        - name: pojo2_name_default
          desc: pojo2_desc_default
# spring.output.ansi.enabled=always ?????
# output:
#     ansi:
#         enabled: always ?????
---
spring:
    profiles: prod
testproperties:
    name: park_yml_profile_prod
    pojoList:
        - name: pojo1_name_prod
          desc: pojo1_desc_prod
        - name: pojo2_name_prod
          desc: pojo2_desc_prod
        - name: pojo2_name_prod
          desc: pojo2_desc_prod
---
spring:
    profiles: dev
testproperties:
    name: park_yml_profile_dev
    pojoList:
        - name: pojo1_name_dev
          desc: pojo1_desc_dev